name: "Test"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test build (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - /data/homeassistant-samsung-frametv-artchanger
          - /data/llm_proxy
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --aarch64 \
            --amd64 \
            --target ${{ matrix.target }} \
            --docker-hub timminater
